/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/v6RyIF8aBrq
 */
import Link from "next/link"
import { CardContent, Card } from "@/components/ui/card"

export function Portfolio() {
  return (
    <div className="flex flex-col min-h-screen">
      <header className="flex h-14 items-center justify-between px-4 md:px-6">
        <Link className="flex items-center gap-2" href="#">
          <MountainIcon className="h-6 w-6" />
          <span className="sr-only">Acme Inc</span>
        </Link>
        <nav className="hidden md:flex gap-4">
          <Link className="text-sm font-medium hover:underline underline-offset-4" href="#">
            Work
          </Link>
          <Link className="text-sm font-medium hover:underline underline-offset-4" href="#">
            About
          </Link>
          <Link className="text-sm font-medium hover:underline underline-offset-4" href="#">
            Contact
          </Link>
        </nav>
      </header>
      <main className="flex-1">
        <section className="w-full py-12 md:py-24 lg:py-32">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl lg:text-6xl/none">
                  John Doe
                </h1>
                <p className="mx-auto max-w-[700px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                  Designer. Developer. Creator.
                </p>
              </div>
              <div className="space-x-4">
                <Link
                  className="inline-flex h-9 items-center justify-center rounded-md bg-gray-900 px-8 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-gray-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-50/90 dark:focus-visible:ring-gray-300"
                  href="#"
                >
                  Contact
                </Link>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32">
          <div className="container grid items-center justify-center gap-4 px-4 text-center md:px-6 lg:gap-10">
            <div className="space-y-3">
              <h2 className="text-3xl font-bold tracking-tighter md:text-4xl">Projects</h2>
              <p className="max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                A selection of my latest work.
              </p>
            </div>
            <div className="grid w-full grid-cols-2 lg:grid-cols-3 items-start gap-8 lg:gap-12">
              <Card>
                <CardContent className="flex flex-col space-y-4">
                  <img
                    alt="Project 1"
                    className="aspect-video overflow-hidden rounded-xl object-cover object-center"
                    height="310"
                    src="/placeholder.svg"
                    width="550"
                  />
                  <div className="space-y-2">
                    <h3 className="text-lg font-bold">Project 1</h3>
                    <p className="text-sm text-gray-500 dark:text-gray-400">A description of the project.</p>
                  </div>
                </CardContent>
              </Card>
              <Card>
                <CardContent className="flex flex-col space-y-4">
                  <img
                    alt="Project 2"
                    className="aspect-video overflow-hidden rounded-xl object-cover object-center"
                    height="310"
                    src="/placeholder.svg"
                    width="550"
                  />
                  <div className="space-y-2">
                    <h3 className="text-lg font-bold">Project 2</h3>
                    <p className="text-sm text-gray-500 dark:text-gray-400">A description of the project.</p>
                  </div>
                </CardContent>
              </Card>
              <Card>
                <CardContent className="flex flex-col space-y-4">
                  <img
                    alt="Project 3"
                    className="aspect-video overflow-hidden rounded-xl object-cover object-center"
                    height="310"
                    src="/placeholder.svg"
                    width="550"
                  />
                  <div className="space-y-2">
                    <h3 className="text-lg font-bold">Project 3</h3>
                    <p className="text-sm text-gray-500 dark:text-gray-400">A description of the project.</p>
                  </div>
                </CardContent>
              </Card>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 border-t">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center space-y-4 text-center">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter md:text-4xl">About Me</h2>
                <p className="max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                  A short bio about me.
                </p>
              </div>
              <div className="space-x-4">
                <Link
                  className="inline-flex h-9 items-center justify-center rounded-md bg-gray-900 px-4 py-2 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-gray-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-50/90 dark:focus-visible:ring-gray-300"
                  href="#"
                >
                  Contact
                </Link>
              </div>
            </div>
          </div>
        </section>
      </main>
      <footer className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t">
        <div className="mx-auto flex gap-4 sm:gap-6">
          <Link className="text-xs hover:underline underline-offset-4" href="#">
            Terms of Service
          </Link>
          <Link className="text-xs hover:underline underline-offset-4" href="#">
            Privacy
          </Link>
        </div>
        <p className="text-xs text-gray-500 dark:text-gray-400">© 2024 Acme Inc. All rights reserved.</p>
      </footer>
    </div>
  )
}


function MountainIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  )
}
