/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/v6RyIF8aBrq
 */
import { Card, CardContent } from "./Card";

export function Portfolio() {
  return (
    <div className="flex flex-col min-h-screen">
      <header className="flex h-14 items-center justify-between px-4 md:px-6">
        <a className="flex items-center gap-2" href="#">
          <MountainIcon className="h-6 w-6" />
          <span className="sr-only">ducktrshessami</span>
        </a>
        <nav className="hidden md:flex gap-4">
          <a className="text-sm font-medium hover:underline underline-offset-4" href="#">
            About
          </a>
          <a className="text-sm font-medium hover:underline underline-offset-4" href="#">
            Contact
          </a>
        </nav>
      </header>
      <main className="flex-1">
        <section className="w-full py-12 md:py-24 lg:py-32">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl lg:text-6xl/none">
                  Josh Wee
                </h1>
                <p className="mx-auto max-w-[700px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                  a.k.a. ducktrshessami
                </p>
              </div>
              <div className="space-x-4">
                <a
                  className="inline-flex h-9 items-center justify-center rounded-md bg-gray-900 px-8 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-gray-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-50/90 dark:focus-visible:ring-gray-300"
                  href="#"
                >
                  Contact
                </a>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32">
          <div className="container grid items-center justify-center gap-4 px-4 text-center md:px-6 lg:gap-10 space-y-5">
            <h2 className="text-3xl font-bold tracking-tighter md:text-4xl">Projects</h2>
            <div className="grid w-full grid-cols-2 lg:grid-cols-3 items-start gap-8 lg:gap-12">
              <Card>
                <CardContent className="flex flex-col space-y-4">
                  <img
                    alt="Project 1"
                    className="aspect-video overflow-hidden rounded-xl object-cover object-center"
                    height="310"
                    src="/placeholder.svg"
                    width="550"
                  />
                  <div className="space-y-2">
                    <h3 className="text-lg font-bold">Project 1</h3>
                    <p className="text-sm text-gray-500 dark:text-gray-400">A description of the project.</p>
                  </div>
                </CardContent>
              </Card>
              <Card>
                <CardContent className="flex flex-col space-y-4">
                  <img
                    alt="Project 2"
                    className="aspect-video overflow-hidden rounded-xl object-cover object-center"
                    height="310"
                    src="/placeholder.svg"
                    width="550"
                  />
                  <div className="space-y-2">
                    <h3 className="text-lg font-bold">Project 2</h3>
                    <p className="text-sm text-gray-500 dark:text-gray-400">A description of the project.</p>
                  </div>
                </CardContent>
              </Card>
              <Card>
                <CardContent className="flex flex-col space-y-4">
                  <img
                    alt="Project 3"
                    className="aspect-video overflow-hidden rounded-xl object-cover object-center"
                    height="310"
                    src="/placeholder.svg"
                    width="550"
                  />
                  <div className="space-y-2">
                    <h3 className="text-lg font-bold">Project 3</h3>
                    <p className="text-sm text-gray-500 dark:text-gray-400">A description of the project.</p>
                  </div>
                </CardContent>
              </Card>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 border-t">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center space-y-6 text-center">
              <div className="space-y-4">
                <h2 className="text-3xl font-bold tracking-tighter md:text-4xl">About Me</h2>
                <div className="max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400 space-y-3">
                  <p>I just like doing things</p>
                  <p>I'm most comfortable with JavaScript/TypeScript but have past experience with C++, Kotlin, Java, and Python. I've also used React and a few SQL databases as a full-stack web developer.</p>
                </div>
              </div>
              <div className="space-x-4">
                <a
                  className="inline-flex h-9 items-center justify-center rounded-md bg-gray-900 px-4 py-2 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-gray-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-50/90 dark:focus-visible:ring-gray-300"
                  href="#"
                >
                  Contact
                </a>
              </div>
            </div>
          </div>
        </section>
      </main>
      <footer className="py-6 w-full px-4 md:px-6 border-t">
        <p className="text-right text-xs text-gray-500 dark:text-gray-400">© Copyright 2024 ducktrshessami</p>
      </footer>
    </div>
  );
}

interface IconProps {
  className: string;
}

function MountainIcon(props: IconProps) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  );
}
