# Build and deploy to GitHub Pages
# https://github.com/JamesIves/github-pages-deploy-action

name: gh-pages build

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: install dependencies
      run: npm ci

    - name: build app
      run: npm run build

    - name: deploy
      uses: JamesIves/github-pages-deploy-action@4.1.0
      with:
        branch: gh-pages
        folder: build
        commit-message: Deploy from ${{ github.sha }}
