# Build and deploy to GitHub Pages
# https://github.com/JamesIves/github-pages-deploy-action

name: gh-pages build

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install dependencies
      run: yarn
    - name: build
      run: yarn build
    - name: deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: build
        commit-message: Deploy from ${{ github.sha }}
